<?php

/**
 * DO NOT EDIT THIS FILE as it will be overwritten by Pbj Compiler process.
 *
 * Registers all of the pbj schemas with the MessageResolver.
 *
 * This file has been auto-generated by the Pbj Compiler on 2016-03-09 22:15:56 CET.
 */

\Gdbots\Pbj\MessageResolver::registerMap([
    'gdbots:pbjx:event:event-execution-failed' => 'Gdbots\Schemas\Pbjx\Event\EventExecutionFailedV1',
    'gdbots:pbjx:request:request-failed-response' => 'Gdbots\Schemas\Pbjx\Request\RequestFailedResponseV1',
    'gdbots:pbjx::envelope' => 'Gdbots\Schemas\Pbjx\EnvelopeV1',
]);
